### ISSUE TITLE
Data Explorer Meta ticket

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1435]
## Design
- [x] Confirm navigation design spec
- [x] Panel restructuring for a more natural flow
  - [x] Move save options & view SQL options to top tool bar
  - [x] Should Column selection panel be on the left?
  - [x] Where should Transformations panel be?
- [x] Column selection panel, how to display links - directed or undirected?

## Backend
- [x] Rudimentary Query endpoint PUT/GET implementation
- [x] Linked table endpoint
- [x] Rest of Query endpoint implementation
- [x] Transformations
   - [x] Limit & Offset
   - [x] Filters
   - [x] Summarization 

## Frontend
- [x] Make sheet component common
- [x] Data Explorer base route & navigation
- [x] Base table selection & panels UI
- [x] Column selection panel
- [x] Add column into results & basic result view
- [x] Result pagination, column selection in result
- [x] Column properties panel
- [x] Transformation panel
   - [x] Filters
   - [x] Grouping & aggregation

## Documentation references
* [Sprint 2 Brainstorming](https://hackmd.io/@mathesar/rkxH9G8d9)
* [Spec for Data Explorer](https://hackmd.io/@mathesar/SJLdTb4K9)
* [Foreign key paths endpoint](https://hackmd.io/@mathesar/SJsgdRNYq)
* [Queries request](https://hackmd.io/@mathesar/H1YSRjEKq)
* [Backend sync with Brent](https://hackmd.io/@mathesar/B1-F1HPt5)
* [UX sync with Ghislaine](https://hackmd.io/@mathesar/Byg2v_dF5)

**Comment by pavish** [comment]
I think we can rename this issue to `Data Explorer` and track Data explorer progress as a feature.

**Comment by pavish** [comment]
Closing this issue since all mentioned tasks are done.
