### ISSUE TITLE
Improve BreadcrumbSelector component

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1516]
## Current behavior

- This is the `BreadcrumbSelector` component:

    ![image](https://user-images.githubusercontent.com/42411/184004827-4bab2c6c-fc23-4768-b50b-1ffd07aa8c03.png)

- It is used both for selecting a Schema within the current Database and for selecting a Table or Exploration within the current Schema.

## Desired behavior

- It should look more like this mockup:

    ![mockup](https://user-images.githubusercontent.com/42411/180277150-e68cf483-9ce5-436f-b347-714937d22295.png)

    Specifically...

    - [x] A search input should exist to filter the entries across all categories. (Done in #1551)
    
    - [x] The search input should be focused when the BreadcrumbSelector opens. (Done in #1558)

    - [x] Users should be able to use `Up`/`Down`/`Enter` keys to select an item while filtering. (Moved to #1646)

    - [x] Entries should highlight the substring of their label which matches the search query. (Done in #1620)

    - [x] Vertical scrolling should not happen so easily. We'll need to increase `max-height` somewhere. A good value might be something like `calc(100vh - 5em)`. (Done in #1560)

    - [x] When the viewport height is small enough to force vertical scrolling within the component, the search input should not scroll -- only the entries. (Done in #1620)

- Additionally (not represented in the mockup)

    - [x] If the URL for the entry matches _the start_ of the router's current URL, then the entry should visually indicate that it's active. (It's important to match the start because we want to show the active schema when we're on the Table Page, for example.) Done in #1576

    - [x] When hovered, each Table entry should have an icon button which opens the Record Selector, navigating the user to the Record Page for their selected record. For this, we'll probably want to add the following property to the `BreadcrumbSelectorEntry` interface:

        ```ts
        interface BreadcrumbSelectorEntry {
          // ...
          button?: { icon: IconProps, label: string, onClick: () => void }
        }
        ```

        (Done in #1620)

It's okay to create small PRs that handle only a portion of these somewhat unrelated improvements.
