### ISSUE TITLE
Data Explorer frontend - Demo video readiness

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1595]
The following checklist is a set of bugs and enhancements for Data Explorer's demo video readiness
- [x] Use RPC style endpoint, add Save button
- [x] Decide and implement default summarization when user navigates from grouped table result to Data Explorer, showing record summaries
  - [x] Default summarization should show count

Related meeting notes: [Record summaries in data explorer](https://wiki.mathesar.org/en/meeting-notes/2022-09#h-2022-09-02-record-summaries-in-data-explorer)

**Comment by pavish** [comment]
I've moved the remaining items to https://github.com/centerofci/mathesar/issues/1597, so I'm closing this issue in favor of that.
