### ISSUE TITLE
2022-09-07 Demo Readiness meta issue

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1604]
### Design - @ghislaineguerin 
- [ ] https://github.com/centerofci/mathesar/issues/1640
- [ ] https://github.com/centerofci/mathesar/issues/1641
- [ ] https://github.com/centerofci/mathesar/issues/1642

### Frontend - @pavish 
- [ ] #1647
- [ ] https://github.com/centerofci/mathesar/issues/1595

### Frontend - @rajatvijay
- [ ] #1650
- [x] Open Db page when Mathesar is opened
- [ ] https://github.com/centerofci/mathesar/issues/1648
- [ ] https://github.com/centerofci/mathesar/issues/1649

### Backend - @mathemancer 
- [x] Database page
    - [x] expose object descriptions (schemata, read/write)
    - [x] add table count and exploration count to schema list endpoint
- [x] Schema page
    - [x] expose object descriptions (tables, read/write)
    - [x] add table count and exploration count to schema detail endpoint
- [x] Data import page
    - [x] potential API work for removing column

### Notes on navigation design
We should redesign navigation once we've gone through the entire storyboard, but here are the notes we've come up with so far:
- Add current page to breadcrumb
- On the schema page, it's not clear how to get to other schemas
- Table features are not discoverable
- The schema icon + name should do what the little triangle does right now
- Database name in header is confusing, we should have some other solution for orienting the user to which Mathesar installation they are in

**Comment by seancolsen** [comment]
> The schema icon + name should do what the little triangle does right now

Can someone clarify this point?

**Comment by kgodey** [comment]
@seancolsen We thought the small triangle with the magnifying glass made a very small click target for a probably-frequent operation (navigating somewhere else).
<img width="286" alt="Screen Shot 2022-09-09 at 8 56 00 AM" src="https://user-images.githubusercontent.com/287034/189355074-c45286e0-b2be-4a88-87ac-687fab7ea5c5.png">

We wanted to get rid of the triangle and instead transfer opening the navigation menu to a larger click target. We have not come up with a specific design solution yet.

**Comment by seancolsen** [comment]
> small click target for a probably-frequent operation

Makes sense. I'd like to be looped in to review that design work.

**Comment by pavish** [comment]
I moved all data import related tasks to me, from @ghislaineguerin, as I'm already making those changes as part of my PR.

**Comment by kgodey** [comment]
@ghislaineguerin I updated the design notes to be clearer and moved all navigation-related items out of this issue's scope.

**Comment by kgodey** [comment]
I'm going to close this issue. I made separate issues to track items that don't have a PR open.
