### ISSUE TITLE
Users and permissions backend

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#1673]
## Problem

Mathesar currently doesn't support any kind of authentication to use the API, and has not users/permission control (at the Mathesar level; the underlying DB could).

## Proposed solution

We will add users and permissions as per the spec described in the wiki [here](https://wiki.mathesar.org/en/product/specs/users-permissions) .

## Tasks
- [x] Make APIs require authentication - #1742
- [x] Add log in page - #1742
- [x] Add custom user model - #1751
- [x] Add Users CRUD API - #1753
- [x] Add list of permissions for user to Users API - #1774 
- [x] Allow permissions to be updated via API - #1774
- [x] Implement permissions for all APIs
    - [x] `/api/ui/v0/users/` - #1780 
    - [x] `/api/ui/v0/database_roles/` - #1902 
    - [x] `/api/ui/v0/schema_roles/` - #1916 
    - [x] `/api/ui/v0/databases/` - #2061
    - [x] `/api/db/v0/tables/` - #1962
    - [x] `/api/db/v0/queries/` - #1999 
    - [x] `/api/db/v0/links/` - #1997 
    - [x] `/api/db/v0/schemas/` - #1961 
    - [x] `/api/db/v0/databases/`- #2061
    - ~~[ ] `/api/db/v0/data_files/`~~ Doesn't make sense to add permission to Data files as they are not bound to any permissible object.
    - [x] `/api/db/v0/tables/{id}/records/` - #1998 
    - [x] `/api/db/v0/tables/{id}/settings/` - #1993 
    - [x] `/api/db/v0/tables/{id}/columns/` - #1992 
    - [x] `/api/db/v0/tables/{id}/constraints/` - #1963 
    - [x] Double check and make sure all APIs are covered
- [x] Implement reset password mechanism 
    - [x] Allow users to change their own passwords #2052 
    - [x] Allow admins to reset user passwords #2000 
    - [x] Require users to change password after first login #2071 
- [X] Implement logout view - Built in by Django
- [x] ~~Implement default permissions for `public` schema~~ - Not needed, refer https://github.com/centerofci/mathesar/pull/1916#discussion_r1023970448
- ~~[ ] Add additional user data to be saved to User model & API~~ - will be implemented on an as-needed basis in the future

**Comment by kgodey** [comment]
@silentninja I realized that I forgot to put the type suggestions and previews endpoint in this checklist – do they need permissions?

**Comment by silentninja** [comment]
> @silentninja I realized that I forgot to put the type suggestions and previews endpoint in this checklist – do they need permissions?

#1962 Adds permissions for those endpoints too.

**Comment by kgodey** [comment]
Okay thanks @silentninja.

Looks like the only thing left here is the "User data to save" section. We can remove it from the requirements for this issue and implement it later as needed by the frontend.

I've updated the issue description and I'll close this issue. Nice work on getting it all done!
