### ISSUE TITLE
Create easy installation path for Mathesar

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#169]
**Problem**

Users will need to install Mathesar on a server. We should make it really easy for them to do so.

**Proposed solution**

Create an installation script for Mathesar that:
- Walks the user through options to set up Postgres, either:
  - using an existing Postgres installation
  - setting up Postgres from scratch
- Sets up the appropriate databases.
- Sets up the appropriate database users.
- Gets Mathesar's web server up and running.

**Tasks**
- [ ] #2032
- [ ] #2031
- [ ] A help text in the installation CLI that would list the database Privileges needed for Mathesar to function effectively.
- [ ] Easy-to-understand config file for the user to enter the necessary details to start running the Mathesar service.
- [ ] Easy-to-understand config file for the user to enter the necessary details needed to connect Mathesar to an existing Database or create a new Database
- [ ] Create a custom docker image on the Docker hub for Mathesar
- [ ] Make changes to our existing Ansible script so that it can be used as an alternative to our Docker installation.

**Additional context**

See [Assumptions for user role](https://github.com/centerofci/mathesar/discussions/130) discussion.
Refer to the [Email Thread](https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/OhUIkLqOXA8/m/19hxdnHFAQAJ) which contains the discussions and the user flow used for Specing out the Task list

**Comment by mathemancer** [comment]
The implementer should take note of https://github.com/centerofci/mathesar/blob/master/install.py .  While it's not quite as easy as we want, it does have the needed steps (setting up the DB, installing types, etc.).  We could combine the pieces of that script with a `migrate` step to also set up the tables that Django needs.

**Comment by mathemancer** [comment]
Tthis work is now being tracked in #2034
