### ISSUE TITLE
Live demo checklist

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#1906]
## Problem

This is a meta-issue to track things @mathemancer needs to get done for the live demo, in descending order of priority
- [x] Set up multitenancy at the DB level
- [x] Document how that works, ask other devs to try it.
- [x] Set up actual infrastructure for demo. (just use staging?)
- [x] Change demo username / password to `demo` / `demo` - @mathemancer 
- [x] Figure out how website --> live demo transition will work (login, etc.)
  - [x] Design for login page - @ghislaineguerin 
  - [x] https://github.com/centerofci/mathesar-website/issues/6 - @pavish 
- [x] Data set loading improvements
  - [x] Backend
    - [x] #2244
    - [x] https://github.com/centerofci/mathesar/pull/2247
  - [x] ~#2222 + frontend~ - not needed due to backend improvements
- [x] #1923 
- [x] #2225
- [x] #2223
- [x] Find and squish bugs that appear from multitenancy - @mathemancer 
  - [x] https://github.com/centerofci/mathesar/issues/2307 
- [x] Add cronjob to delete demo DBs regularly - @mathemancer 
- [x] Finalize test data sets. - @mathemancer
  - [x] Make Library data set more realistic.
  - [x] Add movie collection data set
  - [x] #2070 
  - [x] #2203
  - [x] Add default column display options, explorations, etc. to all data sets - @mathemancer 
- [x] Reset demo DBs after data sets are finalized

Data sets discussion: https://wiki.mathesar.org/en/meeting-notes/2022-11/2022-11-17-weekly#data-sets-discussion

**Comment by seancolsen** [comment]
I'd like to request the following modifications to column names to make them simpler and more intuitive.

| Table | Current name | Desired new name |
| -- | -- | -- |
| Authors | Author First Name | First Name |
| Authors | Author Last Name | Last Name |
| Authors | Author Website | Website |
| Publications | Publication Year | Year |
| Publishers | Publisher | Name |

_(Instead of creating a new ticket, I'm posting this here at Brent's recommendation.)_

**Comment by seancolsen** [comment]
As for "display options" (or perhaps "metadata" is more appropriate) to configure...

- It would be nice to customize the record summary template for both "Authors" and "Patrons" to show `{First Name} {Last Name}`.
- We might want to put a couple saved explorations in there to give the user a quick sense of what is the Data Explorer is capable of.
- Eventually, I'd like to customize all the column widths. But we don't have that functionality built yet.

**Comment by kgodey** [comment]
I think we should make the database names more human readable since the name is displayed very prominently on the DB page. We could do `mathesar_demo_{num}` or `mathesar_demo_{random_word}` or something like that. If we can do spaces instead of underscores, that would be great too.

![Screenshot 2022-11-11 at 13-44-27 mathesar_dviiwc8o Library Management Mathesar](https://user-images.githubusercontent.com/287034/201409776-aef29d76-3f3f-4f01-b3db-2d19b23c7b3e.png)

**Comment by kgodey** [comment]
We need to add a barcode ID column to the `Items` table. The items table also needs a better record summary, it's currently using the publisher name which is just confusing. I would expect it to be configured as `{Publication Title} ({Barcode ID})` or something similar.

**Comment by kgodey** [comment]
We may also want to set display options to 12 hour time for all `TIMESTAMP` fields for clarity.

**Comment by seancolsen** [comment]
Two things are wrong here:

![image](https://user-images.githubusercontent.com/42411/201435514-25aea99e-8765-4e01-ad2c-a1be4ebe57a0.png)

1. There are no foreign keys. 
2. And the columns are out of order compared to the data I just loaded from the playground repo. ("Title" should be the first non-PK column).

**Comment by seancolsen** [comment]
@kgodey said:

> The items table also needs a better record summary,

I think this will be partially fixed if we fix the column ordering problem that I mentioned above. For me locally, all tables have a sensible choice for the first non-PK column. But on staging the columns are ordered differently. When the "Publications" table has its first non-PK column as "Title" and the "Items" table has its first non-PK column as "Publication", then the item will be summarized the the title (transitively).

**Comment by kgodey** [comment]
The data explorer seems broken entirely in live demo mode (works fine locally).

**Comment by mathemancer** [comment]
> The data explorer seems broken entirely in live demo mode (works fine locally).

It's working for me! (ha.) 

Can you provide more details about how it's not working? I clicked around, and successfully made our overdue checkouts report on staging.

**Comment by mathemancer** [comment]
> The data explorer seems broken entirely in live demo mode (works fine locally).

It's working for me! (ha.) 

Can you provide more details about how it's not working? I clicked around, and successfully made our overdue checkouts report on staging.

**Comment by kgodey** [comment]
@mathemancer does https://staging.mathesar.org/mathesar_dviiwc8o/692/data-explorer/ work for you? Once I select `Patrons` as the table, the column list does not load.

The GET API call to https://staging.mathesar.org/api/db/v0/tables/4844/joinable_tables/ fails (500 error) with traceback:

```
Environment:


Request Method: GET
Request URL: https://staging.mathesar.org/api/db/v0/tables/4844/joinable_tables/

Django Version: 3.1.14
Python Version: 3.9.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mathesar.middleware.CursorClosedHandlerMiddleware',
 'demo.middleware.LiveDemoModeMiddleware']



Traceback (most recent call last):
  File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/var/www/staging.mathesar.org/mathesar/mathesar/exception_handlers.py", line 55, in mathesar_exception_handler
    raise exc
  File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/staging.mathesar.org/mathesar/mathesar/api/db/viewsets/tables.py", line 79, in joinable_tables
    processed_joinable_tables = get_processed_joinable_tables(
  File "/var/www/staging.mathesar.org/mathesar/mathesar/utils/joins.py", line 46, in get_processed_joinable_tables
    joinable_tables = [
  File "/var/www/staging.mathesar.org/mathesar/mathesar/utils/joins.py", line 58, in <listcomp>
    FK_PATH: [
  File "/var/www/staging.mathesar.org/mathesar/mathesar/utils/joins.py", line 59, in <listcomp>
    [Constraint.objects.get(oid=oid).id, reverse]
  File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /api/db/v0/tables/4844/joinable_tables/
Exception Value: Constraint matching query does not exist.
```

**Comment by kgodey** [comment]
May be related to #1924, which is also a GET request returning an error only in live demo mode.

**Comment by mathemancer** [comment]
@kgodey Have you experienced this on the demo server? I'm hoping the clean environment will solve this.

**Comment by kgodey** [comment]
@mathemancer No, I have not. I think it's fine to ignore it unless it happens again.

**Comment by kgodey** [comment]
In general, I think it makes sense to focus on getting the test data sets, display options, explorations, and launch mechanism for the live demo figured out before looking too deeply into bugs.
