### ISSUE TITLE
Set up mathesar.org website

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1930]
### Design
- [ ] Home
- [ ] About Us
- [ ] How it Works - Dev
- [ ] How it Works - Non-dev
- [ ] FAQ
- [ ] Community
- [ ] Roadmap
- [ ] Request installation

### Setup
- [ ] Create repo
- [ ] Set up Jekyll site
