### ISSUE TITLE
Create `install.py` to handle platform-agnostic setup tasks

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2031]
**Problem**

We need an installation script that would guide the user in setting up Mathesar. This script would be responsible for the following tasks

**Tasks**
- [x] Detect and Generate Django SECRET_KEY if missing which will have to be manually saved in the appropriate config file depending on the platform.
- [x]  Create a superuser
- [x] Ask if the user would like to create a new Database
- [x] Ask if the user would connect to an existing Database
- [x] Create a Mathesar Schema and **optionally** Install mathesar types and casting functions on all the User Databases.

**Proposed solution**
Modify our existing `install.py` script to accommodate the above changes.

**Comment by mathemancer** [comment]
Wouldn't we use a config file for holding the credentials? Or are you planning for the installation script to write that file?

**Comment by silentninja** [comment]
> Wouldn't we use a config file for holding the credentials? Or are you planning for the installation script to write that file?

After having a discussion with @mathemancer we decided to have the user manually store the credentials in an appropriate config file based on the deployed platform. We are not planning to do it in this release because the process to store the config credentials varies based on the platform. #2042 has been created to track it, so that it can be implemented in future

**Comment by silentninja** [comment]
Closing this issue as all the tasks are complete and #2449 has been created for the last remaining task which is a nice-to-have
