### ISSUE TITLE
Allow users to install Mathesar using Docker Compose and a brand new DB

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#2034]
## Setup Tasks
This is infrastructure that will also be used for other deployment types.

- [x] Set up separate `docs.mathesar.org` site for documentation.
  - [x] #2117 @dmos62 
  - [x] #2136 @kgodey

## Deployment Type 1

This deployment has the service and all DBs running in Docker containers managed by `docker-compose` as in our current dev setup. It requires a bash prompt, and a working installation of `docker`. It also requires the user to have permissions set up so they can run `docker` commands.

### Installation User Flow

For this deployment type, they should click "Simple installation with Docker (recommended)" link from the "Install Mathesar" page, see some instructions to check and/or install dependencies (`docker` and `docker-compose` for this deployment type) and then a command like:
```sh
curl -s https://raw.githubusercontent.com/centerofci/mathesar/v1.0.0/install/install.sh | bash
```
They should copy and paste that into a terminal window, and follow the prompts. Note that depending on their permissions setup for docker, they will need to use `sudo` to run some commands, and so they'll need to type their password at the appropriate commands (we should also give them info about what they're doing at that point). The reason to avoid piping directly into `sudo bash` is because I'd be grumpy if a website asked me to do it. Then the script should also tell them what the command requiring elevated priveleges will do. We could consider caching the credentials. The script should:

1. Check the `docker` and `docker-compose` versions, and exit non-zero (with a useful message) if they're not going to work.
1. Ask for an installation directory to hold config files (or we could just put it under `$HOME/.config/mathesar` as is tradition)
1. Download appropriate versions of the `docker-compose.yml` and `.env.example` from the repo to the local machine.
1. Move `.env.example` to `.env` and customize it with appropriate secrets and other variables.
   - This section would be interactive so that they can input things like DB keys, etc.
1. Run `docker-compose up <appropriate_service_name>`.
   - This would pull all needed images and start all necessary containers, including a Mathesar-managed DB container.
1. Run `install.py` in the running container.
1. Run migrations (probably as part of `install.py`)
1. Set up a superuser
1. Output information about configuration, and how to connect a browser to Mathesar.

### Installation Flow Tasks
These tasks are needed to make the above user flow possible.
- [x] Document prerequisites and permissions setup for this deployment type on `docs.mathesar.org`.
- [x] Set up docker image and publish to dockerhub for testing.
- [x] #2393
- [x] #2031
- [x] Add help text in the installation CLI that explains setting up the database admin user.
- [x] #2032
- [x] Document use of this setup on `docs.mathesar.org`. @mathemancer 
- [x] Create (and maintain) troubleshooting and FAQs for this deployment type on `docs.mathesar.org`.
- [x] Create (and maintain) command-line upgrade documentation for this deployment type on `docs.mathesar.org`.
- [x] #2510

# Additional context

See [Assumptions for user role](https://github.com/centerofci/mathesar/discussions/130) discussion.
Refer to the [Email Thread](https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/OhUIkLqOXA8/m/19hxdnHFAQAJ) which contains the discussions and the user flow used for initially Speccing out the Task list

**Comment by mathemancer** [comment]
https://github.com/centerofci/mathesar/issues/41/#issuecomment-1340847292

(Replying here to consolidate various discussions)

The main reason to turn off `dev` flags by default is to avoid the super slow startup from the front end. We can consider other methods, but I'd need to think through some implications. The `dev` mode leaks some info, and we'd need to make sure we weren't advising potential users and new admins down an overly dangerous path.

**Comment by kgodey** [comment]
This seems fairly thorough, thanks @mathemancer and @silentninja.

How is this work being divided up? I see everyone on the backend team is assigned.

**Comment by silentninja** [comment]
@kgodey Each of the issues has an assigned person to it. As for the checklist items without GitHub issues, are up for grabs and anyone working on it would add their name next the checklist item

**Comment by kgodey** [comment]
> Each of the issues has an assigned person to it. 

Currently, only one issue has an assigned person next to it. Does that mean everything else is up for grabs?

**Comment by silentninja** [comment]
Only the checklist items without equivalent Github issue will be having a person assigned to it.

**Comment by kgodey** [comment]
I've made the following changes to this issue:
- Removed all assignees except @mathemancer to indicate that @mathemancer is coordinating this.
- Added a checklist item to document the manual upgrade process.
- Moved deployment types 2 & 3 to #2427, which is in the "Launch nice-to-haves" milestone
- Moved upgrade information to #227, which is in the "Launch nice-to-haves" milestone

**Comment by dmos62** [comment]
@kgodey I'm not seeing "a checklist item to document the manual upgrade process". Am I looking in the wrong places or did it get lost?

**Comment by kgodey** [comment]
@dmos62 It's the last checklist item before the "Additional Context" header.

**Comment by mathemancer** [comment]
Okay, everything here should be done now.

**Comment by ovizii** [comment]
Any chance to get a docker/compose.yml installation method without any bash scripts involved_

I asked this on your announcement post in the selfhosted reddit and the answer was that you are working on it: https://www.reddit.com/r/selfhosted/comments/11n2fxx/comment/jbomlgl/

Is there an issue I can track somewhere, or should I open an issue for it?

**Comment by pavish** [comment]
@ovizii

> Any chance to get a docker/compose.yml installation method without any bash scripts involved_
> Is there an issue I can track somewhere, or should I open an issue for it?

We're currently focusing improving installation methods for our next release. This particular issue is being handled but it's not tracked as an issue. **It'll be great if you could open an issue for it.**

Regarding the instructions to run Mathesar using docker-compose.yml without the bash script, here's a comment from another thread with the steps you could follow: https://github.com/centerofci/mathesar/issues/2741#issuecomment-1482598608

cc: @silentninja @ghislaineguerin @kgodey
