### ISSUE TITLE
Data Explorer styling & frontend granular meta issue

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2036]
This meta issue tracks pending items in Data Explorer prioritized by demo video readiness

1. **The following are essential for the demo video, since they will be visible during the demo**
    - [x] Show cell content on the Cell inspector tab - DEMO VIDEO
    - [x] Automatically select inspector tabs based on column selection/cell selection - DEMO VIDEO
    - [x] Format content in cells based on display_options from underlying table - DEMO VIDEO
    - [x] Implement Hide transformation - DEMO VIDEO
    - [x] Show auto summarization modal when user clicks on a column with one-to-many link - DEMO VIDEO
    - [ ] ~~Style save exploration modal - DEMO VIDEO~~ Tracked separately
    - [x] Add save & close dropdown option to save button - DEMO VIDEO
    - [x] Show save status indicator when unsaved changes are present - DEMO VIDEO
    - [x] Show initial help tutorial when user opens Data Explorer for the first time - DEMO VIDEO

    1.1 *The following are essential for demo, but will take more effort & planning. We should try to de-prioritize some items here if we can safely exclude from the demo video*
      - [x] Format array cell content based on display_options - DEMO VIDEO

2. **Following are part of styling & frontend issues, but doesn't necessarily block the demo video, based on the initial script. But they many be visible during the demo, so we need to decide if we want to prioritize any of them**
    - [x] Do not allow last base table column to be deleted - INITIAL RELEASE
    - [x] Implement Sort transformation - INITIAL RELEASE
    - [x] Show tooltips with help icon: - INITIAL RELEASE
      - [x] Near base table name - INITIAL RELEASE
      - [x] Near column count indicator in left pane - INITIAL RELEASE
    - [ ] Show error message when columns are missing in underlying table - INITIAL RELEASE
    - [x] Show error message when filters are empty/invalid and user performs additional operations - INITIAL RELEASE
    - [x] Show count in the column selection left pane for added columns - INITIAL RELEASE
    - [x] Show array icon in left pane for columns with one-to-many links - INITIAL RELEASE
       - ~~Not sure if this is required, since we ask for explicit confirmation from user~~
       - ~~@ghislaineguerin  agreed with not showing the array icon in left pane, but it was not finalized~~
       - @kgodey:  we should do this

**Comment by pavish** [comment]
@kgodey It'll be great if you could take a look at the items in the description and help me prioritize them better, based on your expectations for the demo video

**Comment by kgodey** [comment]
@pavish I annotated the list above with priorities, please feel free to reformat as desired.
