### ISSUE TITLE
Users & Permissions frontend

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2205]
Refer RFC for implementation details
  - [PR link](https://github.com/centerofci/mathesar-wiki/pull/75)
  - Wiki link to be updated after RFC is merged

### Users
- [x] Base API utility for users - @pavish
- [x] Stores needed for user profile - @pavish
- [x] User profile route & page - @pavish
- [x] Administration route & pages - @pavish
- [x] Listing route functionality - @pavish
- [x] Add/Edit route functionality - @pavish
- [x] Style admin page - @rajatvijay 
- [x] Style user listing page -  @rajatvijay 
- [x] #2430 @seancolsen
- [x] #2428 @seancolsen
- [x] #2431 @seancolsen
- [x] #2027 - @pavish
- [x] #2448 @seancolsen
- [x] #2404 - @pavish

### Permissions
- [x] #2470 - @pavish
- [x] #2471 - @pavish
- [x] #2472 - @pavish
- [x] #2473 - @pavish
- [x] #2474 - @pavish
   - Admin route 
   - Import upload and preview routes
   - Record page route
   - Exploration edit route
- [x] #2475 - @pavish
- [x] #2446 - @seancolsen 
- [x] #2476 - @rajatvijay 
   - Editing the spreadsheet
   - Adding new columns
   - Operations in right-click context menus
- [x] #2477 - @rajatvijay 
- [x] #2478 - @pavish
- [x] #2447 - @seancolsen 
- [x] #2479 - @pavish
- [x] #2480 - @pavish

Blocked by:
- https://github.com/centerofci/mathesar/issues/2311
- https://github.com/centerofci/mathesar/issues/2323
- https://github.com/centerofci/mathesar/issues/2321
- https://github.com/centerofci/mathesar/issues/2392

Non-blocking backend work:
- https://github.com/centerofci/mathesar/issues/2312

See also:
- #1673 
- #1985
