### ISSUE TITLE
Finishing setting up mathesar-update-companion repo

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2209]
Following repo has been spun up for our update companion container: https://github.com/centerofci/mathesar-update-companion

The repo might need additional setting up.

### Tasks
- [x] Standardize branch names
- [x] Set up access permissions correctly
- [x] Set up GitHub workflows (sync files from main repo)
- [x] Set up label & milestone sync
- [x] Remove "fork" status
- [x] Set up repo settings - merge types, automatic delete of head branches, etc.
- [x] Verify new labels and milestones
- [x] Delete default labels that we don't use
- [x] Close milestones as needed
