### ISSUE TITLE
Implement upgrades for deployment type 1

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#227]
*Please see #2034 and #2427 for information about deployment types.*

### Problem

We aim to release Mathesar frequently after the alpha release. Users will need to know how to upgrade to new versions.

### Specification
Automatic updating right now will _only_ handle:

- Checking non-`pip`-installable dependency versions and complaining if needed.
- Updating versions of `pip`-installable packages.
- Updating our actual Mathesar python code to the latest release.
- Adding functions / types to the user database if needed.

It will _not_ handle:

- Upgrading non-`pip`-installable dependencies (e.g., `docker` or `postgresql`).
- Modifying the user database in a non-additive way (e.g., changing a type).

### User Flow
*This user flow is still under discussion and not yet finalized.*

- Within an hour of a new image existing on DockerHub, admin user sees a notification that there's an update available
  - The notification should be visible from anywhere in the app, but the specific spot on the screen is yet to be determined.
- They click on the notification, and are sent to the `upgrade` admin panel page.
- They see info about the version they're running, and the new version.
  - Info should include:
    - Current version, publication date
    - Newest available version, publication date
    - Link to change notes.
- They click an 'update' on the admin panel page.
- They see a warning about downtime, potential breakages, etc.
- They confirm.
- They see a spinner and wait.
- If success, they see 'success'
- If fail, they see 'fail; please retry by clicking here, or go to docs.mathesar.org/troublshooting#update-problems'

```[tasklist]
## Tasks
- [ ] #2395 
- [ ] #2408 
- [x] #2045
- [x] #2100
- [x] #2137
- [x] #2127
- [ ] https://github.com/centerofci/mathesar/issues/2396
- [ ] https://github.com/centerofci/mathesar/issues/2485
- [ ] https://github.com/centerofci/mathesar/issues/2492
- [ ] https://github.com/centerofci/mathesar/issues/2534
```

**Comment by kgodey** [comment]
I've made the following changes to this issue:
- Renamed to focus on deployment types 1 & 2
- Moved spec into this issue
- Moved to launch nice-to-haves milestone

**Comment by dmos62** [comment]
All tasks complete.
