### ISSUE TITLE
Usability testing for basic Mathesar features

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2435]
- [x] Come up with scenarios
- [x] Run tests
- [x] Process and analyze tests - https://hackmd.io/@mathesar/B1aXELfpj
- [x] Put usability testing videos on our Google Drive
- [x] Create GitHub issues for launch blockers or nice-to-have
- [x] Decide if we need to run additional tests – *we're not doing further tests*

**Comment by ghislaineguerin** [comment]
@kgodey Issue #2490 has been created
