### ISSUE TITLE
Update deployment docs

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2589]
## General tasks
- [x] Add more info on connecting existing databases
- [x] Consider including Ansible playbooks to set up OS with Docker
- [x] Consider integrating Windows guide (written by Ben)

## Usability tests - feedback
- [x] ~Add `wget` to prerequisites. It's not there by default on Debian.~ - tracked in #2572 
- [x] ~Add more detail about how to achieve a "clean Docker state"~ will be handled by #2585
- [x] ~Add more explanation/justification around `sudo` use by script~ - done in previous updates
- [x] Set `/etc/mathesar` to the default for copy/pasting start/stop commands.
- [x] List operating systems on which we have tested Mathesar
- [x] Emphasize that Mathesar is alpha software and issues should be opened on GitHub
- [x] Issues from [WB testing report](https://docs.google.com/document/d/1brAzWeIr-PYH6NJFdxTM21suk0cUmhiR/edit)
  - [x] Rename "Installl with Docker Compose" to just "Installation"
  - [x] Swap positions of start/stop Mathesar commands
  - [x] Improve precision of Database Configuration step 
  - [x] Improve precision of Webserver Configuration step
  - [x] Add recommended permissions to Configuration directory step
  - [x] Fix typo in Docker containers section
  - [x] Ports section
    - [x] ~Explain clean docker state~  will be handled by #2585
    - [x] Suggest non-default ports
