### ISSUE TITLE
Frontend implementation of foreign key constraints

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#263]
## Sub-tasks

- [ ] #948 (for Scenario 1b)
- [ ] #947 (for Scenario 1a)
- [ ] #949 (for Scenario 2a)
- [ ] #951 (for Scenario 2)
- [ ] #950 (for Scenario 3a)
- [ ] #952 (for Scenario 3b)
- [ ] #953 (for Scenarios 4a and 4b)
- [ ] #955 (for Scenarios 4 and 5)
- [ ] #954 (for Scenarios 5a and 5b)

## Functionality in spec which already works

- Allow user to delete FK constraints from the table constraints dialog (for Scenario 2a)

## Additional context

- [Foreign Key Constraints Spec](https://wiki.mathesar.org/en/design/specs/foreign-key-constraints)
- back-end meta ticket: #451

**Comment by kgodey** [comment]
Moving this to the Views milestone because we should be creating views to make things easier for the user while working with relationships.
