### ISSUE TITLE
RSQLA1: Move DDL Operations to SQL Functions

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#2737]
This is the first project in the removing SQLAlchemy metaproject.

This issue and issues downstream (i.e., linked) are the source of truth for any work included in this project until further notice.

This project should proceed in phases. These have some overlap, but they should proceed generally in order.

## Phase One: Create DDL functions in database

During this phase, the goal is to create the bulk of needed DDL functions in the database. Examples of such functions can be found in the file `db/sql/0_msar.sql`. Please use the docstring style there.

During this phase, you can either use the function in a python wrapper (see examples in `db/tables/operations/alter.py`) or you can put a **`# TODO`** where the function will be wrapped. The heuristic should be whether you'll have do do a bunch of extra work with tests and dependencies to wrap the function in Python. If so, skip it. If not, go ahead and do the wrapper.

### Issues

- [x] db.columns.operations.alter
- [x] db.columns.operations.create
- [x] db.columns.operations.drop
- [x] db.constraints.operations.create
- [x] db.constraints.operations.drop
- [x] db.links.operations.create
- [x] db.schemas.operations.alter
- [x] db.schemas.operations.create
- [x] db.schemas.operations.drop
- [x] db.tables.operations.alter
- [x] db.tables.operations.create
- [x] db.tables.operations.drop
- [x] db.tables.operations.split

## Phase Two: Replace remaining Python DDL functions with thin wrappers

During this phase, the goal is to finish up using the DB functions via thin python wrappers. Minimal logic should remain in Python, only to link up function signatures. Avoid major function signature changes in this phase. If any DB functions are missing, write them (of course). It's completely fine to create scaffolding functions at this point.

Checking off an item in this phase implies there are no remaining `sqlalchemy` imports in the module.

### Issues

**TODO**: make issues. The below modules should all be covered. Note that you may bleed into other modules. Use your judgement. Avoid sprawl.

- [x] db.columns.operations.alter
- [x] db.columns.operations.create
- [x] db.columns.operations.drop
- [x] db.constraints.operations.create
- [x] db.constraints.operations.drop
- [x] db.links.operations.create
- [x] db.schemas.operations.alter
- [x] db.schemas.operations.create
- [x] db.schemas.operations.drop
- [x] db.tables.operations.alter
- [x] db.tables.operations.create
- [x] db.tables.operations.drop
- [X] db.tables.operations.split

## Phase Three: Refactor and clean up

This phase will be a bit more ad-hoc, and thus has no attendant issues or modules. The goal is to be able to check the following boxes:
- [x] The functions from modules above should have all SQLAlchemy objects removed from their function signatures.
- [x] Delete unneeded scaffolding and functions.

# Additional context

The project is also [on the wiki](https://wiki.mathesar.org/en/projects/sql-ddl-operations.md). See the description there for some justifications for the project's existence as well as a big-picture view of the goals and phases.

**Comment by Wali-Muhammad123** [comment]
Hi, I want some more insight into this project. I am very much interested in it. Could I be provided some info it?

**Comment by mathemancer** [comment]
@Wali-Muhammad123 

To start, please note that we're not yet ready for outside contributors on this issue (it's still in draft state).

We're planning a major reorganization of the back end code base. We're planning to remove SQLAlchemy, thereby reducing the state we need to maintain in the python layer. See [the wiki page](https://wiki.mathesar.org/en/projects/sql-ddl-operations.md) for more details about the portion of that larger project associated with this issue.

**Comment by mathemancer** [comment]
I'm removing everything related to column moving from this issue, since it didn't make sense to move the current logic to SQL without first handling the logic and product work needed. This work will be tracked in #3152 .

**Comment by mathemancer** [comment]
All tasks are complete, or split off into separate issues. Closing.
