### ISSUE TITLE
Prepare issues for rewriting our DDL operations to not use sqlalchemy

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2756]
Relevant project: https://wiki.mathesar.org/en/projects/sql-ddl-operations.md

We want to split up the rewrite of our DDL operations into many small PRs, so as to make review more manageable and the whole process more iterative.

Planning the issues, implies planning in what order changes should be applied. For example, `db.columns.operations.alter:batch_update_columns` depends on almost all functions in its module, and thus rewriting it would require changes to the rest of the file, but for example `db.columns.operations.alter:set_column_default` is used by many functions in that namespace, but doesn't call anything in that namespace. However, `set_column_default` calls a lot of things outside its namespace, so it might not be the best place to start making changes either.

### Tasks

- [ ] Find the best places to start the rewrites
- [ ] Prepare issues for those rewrites
- [ ] In advance, find the next best places to continue rewrites
- [ ] Loop

**Comment by dmos62** [comment]
A few more places to start the rewriting. Including a basic idea for how to structure getting rid of mathesar-layer's dependence on SA objects in a piece-meal way (by finding db-layer methods that return an SA object, and rewriting to return something else).

```
remove sa, good places to start, continued
  - stop returning SA objects from public db-layer interfaces
    - subdivides into subtasks that should roughly correspond to the different SA objects we pass around
    - e.g.
      - db/tables/operations/select.py::reflect_table
      - db/columns/operations/create.py
    - implies some mathesar-layer refactors
      - hopefully minor
  - various dropping-related namespaces
    - e.g.
      - db/tables/operations/drop.py
      - db/columns/operations/drop.py
    - they won't return anything
      - thus fairly isolated
```

@mathemancer if all this makes sense, I think we can start writing issues. What do you think?

**Comment by dmos62** [comment]
Closing, because @mathemancer seems to have a handle on this and only I was using this threading.
