### ISSUE TITLE
Document additional installation options

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2789]
Issues related to the Installation Improvement 

```[tasklist]
### Tasks with code changes
- [ ] #2788
```
```[tasklist]
### Documentation Tasks
- [ ] https://github.com/centerofci/mathesar/issues/2784
- [ ] https://github.com/centerofci/mathesar/issues/2783
- [ ] https://github.com/centerofci/mathesar/issues/2761
- [ ] https://github.com/centerofci/mathesar/issues/2427
- [ ] #2785 
- [ ] #2787
```

**Comment by pavish** [comment]
I'm closing this since all items are merged.
