### ISSUE TITLE
Support for importing JSON

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2894]
Part of [GSoC 2023 project for supporting the import of JSON and Excel into Mathesar](https://wiki.mathesar.org/en/community/mentoring/project-ideas/import-excel-json-files).

```[tasklist]
- [x] https://github.com/centerofci/mathesar/pull/2890
- [ ] Merge essential utility functions to get perfect JSON working
- [ ] Update functions that insert data into tables
- [ ] Merge API tests for everything written until this point
- [ ] Merge functions to convert invalid JSON structures to valid one
- [ ] Merge JSON normalization code and return correct errors from backend
- [ ] Merge remaining tests
- [ ] Improve UI for better user understanding of the new feature
- [ ] Display errors properly
```

**Comment by IamEzio** [comment]
🚀
