### ISSUE TITLE
Support for importing JSON

### ISSUE THREAD

**Issue by IamEzio** [centerofci/mathesar#2895]
Part of [GSoC 2023 project for supporting the import of JSON and Excel into Mathesar](https://wiki.mathesar.org/community/gsoc/project-ideas/import-excel-json-files).

Expected outcomes once this issue is completed: Users should be able to upload JSON files in the current import UI seamlessly. If the file is structured so that it cannot be imported, they should see a clear error message explaining why.

```[tasklist]
- [x] https://github.com/centerofci/mathesar/pull/2890
- [ ] https://github.com/centerofci/mathesar/pull/2906
- [x] Merge API tests for everything written until this point #2933
- [x] Merge JSON normalization code and return correct errors from backend #2968
- [x] Merge remaining tests #2977
- [x] Create Documentation for types of allowed JSON #2992
- [ ] Improve UI for better user understanding of the new feature #3008
- [ ] #3039
```

**Comment by seancolsen** [comment]
Closing as the remaining work is tacked in #3031
