### ISSUE TITLE
Add more summarization functions

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#2917]
Currently, Mathesar supports two aggregation functions (`Distinct list` & `Count`) as transformation steps while summarizing columns. 

This summer, my mentors, @mathemancer, @seancolsen and I will be adding a lot of them as a part of the **GSoC '23 project, [Add more summarization functions](https://wiki.mathesar.org/en/community/mentoring/project-ideas/more-summarizations)**. 

This meta issue tracks all the feature requests (and linked pull requests) I will work on.
```[tasklist]
### Tasks
- [ ] #2892
- [ ] #2909
- [ ] #2913
- [ ] #2915
- [ ] https://github.com/centerofci/mathesar/issues/2931
- [ ] https://github.com/centerofci/mathesar/issues/2918
- [ ] https://github.com/centerofci/mathesar/issues/2944
- [ ] https://github.com/centerofci/mathesar/issues/2980
- [ ] https://github.com/centerofci/mathesar/issues/3005
- [ ] #3106 
```

**Comment by Aritra8438** [comment]
Completed!
