### ISSUE TITLE
`Distinct List` aggregation not working properly for some datatypes.

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#2962]
## Description
When the distinct list transformation is applied to some column types, it produces some inconsistencies.
- for the `Duration` columns, it results in `NaN:NaN`.
- for the `Time with timezone` columns, it results in an error.
- for the `json_list` column, it results in some pills of characters (rather than pills of strings or arrays)
- for the `date_time with timezone` columns, it produces pills with raw date_time format. 

## Expected behavior
- Maybe, the best way to handle this is to represent them in the same format as they are represented in the table.
- Alternatively, casting them to more general types (like `TEXT` or `Numeric`) might work.

```[tasklist]
### Tasks
- [ ] https://github.com/centerofci/mathesar/issues/2963
- [ ] https://github.com/centerofci/mathesar/issues/2964
- [ ] https://github.com/centerofci/mathesar/issues/2965
- [ ] https://github.com/centerofci/mathesar/issues/2966
```

**Comment by Aritra8438** [comment]
Hi, @mathemancer and @seancolsen.

Here are some of the inconsistencies, I have noticed.

**Comment by Aritra8438** [comment]
Hi @mathemancer, @seancolsen, @dmos62. Here are some observations that might be helpful.

**This is the API response while fetching the records for a table:**

```JSON
{
    "count": 3,
    "grouping": null,
    "preview_data": null,
    "results": [
        {
            "1898": "13:50:15.342262Z",
            "1911": "2023-06-22T06:30:00.0Z AD",
            "1864": 1,
            "1925": "P0Y0M0DT0H40M0S",
            "1996": "a"
        },
        {
            "1898": "13:55:19.152341Z",
            "1911": "2023-06-08T06:30:00.0Z AD",
            "1864": 2,
            "1925": "P0Y0M0DT0H3M20S",
            "1996": "a"
        },
        {
            "1898": "12:00:00.0Z",
            "1911": "2023-06-30T09:50:00.0Z AD",
            "1864": 3,
            "1925": "P0Y0M0DT0H0M2S",
            "1996": "b"
        }
    ]
}
```
 
**This is the API response while fetching the records for an exploration:**
```JSON
"records": {
        "count": 2,
        "grouping": null,
        "preview_data": null,
        "results": [
            {
                "Date_time_Grp_grouped": "a",
                "Date_time_Duration_agged": [
                    "200.0",
                    "2400.0"
                ],
                "Date_time_Date-Time_agged": [
                    "2023-06-08T06:30:00Z",
                    "2023-06-22T06:30:00Z"
                ],
                "Date_time_Time_agged": [
                    "13:50:15.342262",
                    "13:55:19.152341"
                ]
            },
            {
                "Date_time_Grp_grouped": "b",
                "Date_time_Duration_agged": [
                    "2.0"
                ],
                "Date_time_Date-Time_agged": [
                    "2023-06-30T09:50:00Z"
                ],
                "Date_time_Time_agged": [
                    "12:00:00"
                ]
            }
        ]
    },
```
Indeed, they are different.

Also, I noticed that records (of type `TypeDecorators`) are not cast to any **TEXT / Underlying Type**, their types are preserved until the very end before cast to string by Response object (which might simply do `str(record)`).
As `Time with Timezone` can not be JSON serialized, doing the same throws an error.

Even if they are the same, the frontend representation seems to be different for the table and data-explorer.

**Comment by seancolsen** [comment]
I'm closing this because the work seems to be sufficiently tracked in separate tickets and I don't see a need for a meta ticket to organize them at this stage.
