### ISSUE TITLE
Improve and organize error handling

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#2979]
## Problem

Currently much of the error handling in our codebase is pretty ad-hoc. It's tricky to figure out which part of the stack is dealing with a given exception. Also, many exceptions aren't informational enough for the user to determine the solution.

## Proposed solution

We should
- [ ] Discuss among the back end devs how we want to organize this
- [ ] Implement (depending on above discussion) custom SQL layer exceptions that give more info that the python layer can pick up
- [ ] Organize where/how the errors are transformed into API errors.

## Additional context

PostgreSQL has pretty good facilities for writing custom exceptions to be raised. We'd have to relegate ourselves to `plpgsql` (rather than `sql` functions to use them.

https://www.postgresql.org/docs/15/plpgsql-errors-and-messages.html
