### ISSUE TITLE
2023-07 Backend fixes

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#3022]
Meta ticket for [2023-07 backend fixes project](https://wiki.mathesar.org/en/projects/2023-07-backend-fixes).

```[tasklist]
# Block-prone tasks
- [ ] https://github.com/centerofci/mathesar/issues/2245
- [ ] https://github.com/centerofci/mathesar/issues/1370
- [ ] https://github.com/centerofci/mathesar/issues/3128
- [ ] https://github.com/centerofci/mathesar/issues/3024
```

```[tasklist]
# Block-proof tasks
- [ ] https://github.com/centerofci/mathesar/issues/2983
- [ ] https://github.com/centerofci/mathesar/issues/2724
- [ ] https://github.com/centerofci/mathesar/issues/3013
```

Some of the primary tasks of the project were user-reported bugs/tickets. They were derived into action tickets and are tracked separately below, because closing them and closing the derived action ticket is not the same.

```[tasklist]
### Related user-reported tickets
- [ ] https://github.com/centerofci/mathesar/issues/2754
```

Tasks that may have been primary parts of the project but have been degraded in importance due to changes to code or circumstance:

```[tasklist]
### Nice-to-haves
- [ ] https://github.com/centerofci/mathesar/issues/2959
- [ ] https://github.com/centerofci/mathesar/issues/3007
```

**Comment by dmos62** [comment]
This issue was used for tracking work in a cycle. Now that the cycle is finished, I'm closing the issue.

**Comment by dmos62** [comment]
Also, moved tasks that won't be finished for next release to backlog.
