### ISSUE TITLE
Support for importing Excel files

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#3027]
Part of [GSoC 2023 project for supporting the import of JSON and Excel into Mathesar](https://wiki.mathesar.org/community/gsoc/project-ideas/import-excel-json-files).

Expected outcomes once this issue is completed: Users should be able to upload Excel files in the current import UI seamlessly. If the file is structured so that it cannot be imported, they should see a clear error message explaining why.

```[tasklist]
- [ ] #3059
- [ ] #3083
- [x] Merge Excel normalization code #3132 
- [x] Merge remaining tests #3132 
- [x] Add `sheet_number` param in datafile API to accept the sheet number to use in the Excel file #3195 
- [ ] Create Documentation for types of allowed Excel #3204 
- [ ] Improve UI for better user understanding of the new feature #3211 
```

**Comment by seancolsen** [comment]
Closing as the remaining work is tacked in #3031
