### ISSUE TITLE
Implement 'Shares'

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#3032]
## Issues
- [x] https://github.com/centerofci/mathesar/issues/3033
- [x] https://github.com/centerofci/mathesar/issues/3034
- [x] https://github.com/centerofci/mathesar/issues/3035
- [x] https://github.com/centerofci/mathesar/issues/3036

## Tasks:
- [ ] Add regenerate slug endpoints

### https://github.com/centerofci/mathesar/pull/3093#pullrequestreview-1546069582
- [ ] Address the following in shared table consumer page
   - [ ] Disable re-reordering of columns
   - [ ] Don't show the icon hyperlink to the record page within the PK cell
   - [ ] Remove the following entries in the cell context menu:
       - "Set to NULL"
       - "Go to Record Page"
       - "Go to Linked Record" (shown only for FK columns)
   - [ ] Remove the "Go to Record Page" entry from the row header context menu
   - [ ] Disable record selector in filtering for FK columns
- [ ] Come up with a better term for 'ShareConsumer'. Some suggestions:
    - ShareAccessInfo
    - SharedLink
    - ConsumableShare

## Related:
* [Product spec](https://wiki.mathesar.org/en/product/specs/publicly-shareable-links)
