### ISSUE TITLE
Improve support for unknown types

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#3095]
## Problem
If a type is unknown to Mathesar (i.e. not hardcoded in Mathesar), it is currently a second-class type with limited support. [See this comment](https://github.com/centerofci/mathesar/pull/3040#issuecomment-1641819243) for overview of what is meant by limited support at the time of writing.

Basically, an unknown type currently:
- doesn't get its actual type identifier reported; is not distinguishable from other unknown types;
- any unhardcoded type doesn't have hints or metadata necessary to tell frontend what UI type it is categorized as, what filters (or other features) may be applied to it.

## Proposed solution

```[tasklist]
- [ ] Report actual type of unhardcoded types
- [ ] https://github.com/centerofci/mathesar/issues/2959
- [ ] https://github.com/centerofci/mathesar/issues/3007
- [ ] Expand the number of types we have hints/metadata/hardcodings for
```

**Comment by mathemancer** [comment]
Okay, finally found the best place for this comment. Sorry for the repetition. I think we can get some benefits by detecting the DB-level code giving information about the type. See [this comment](https://github.com/centerofci/mathesar/pull/3040#issuecomment-1651023079) for more info.
