### ISSUE TITLE
2023-08 Backend fixes

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#3144]
These are candidate tasks for backend fixes during cycle 2 starting in 2023-08.

Below issue list is ordered and categorized according to perceived priority.

Sorting and categorization is done with following presumptions in mind,
- unblocking frontend is most important, because frontend's highest-priority work depends on backend work,
- bugs are higher priority than improvements,
- user-reported bugs are higher priority than other bugs,
- user-requested improvements are higher-priority than other improvements.

Therefore, the idea is, given below categorized list, to do higher tasks in higher categories first, if possible.

```[tasklist]
# [What frontends needs to be unblocked](https://github.com/centerofci/mathesar/issues/3151)
- [ ] https://github.com/centerofci/mathesar/pull/3186
- [ ] https://github.com/centerofci/mathesar/issues/2844
```

```[tasklist]
# User-reported bugs
- [ ] https://github.com/centerofci/mathesar/issues/3109
- [ ] https://github.com/centerofci/mathesar/issues/3112
```

Supabase research is part of this cycle's work and is deemed less important than above tasks. Analogous frontend effort also has it on their task list, so whoever gets to it first, gets to do it.

```[tasklist]
# Supabase research
- [ ] https://github.com/centerofci/mathesar/issues/3141
```

```[tasklist]
# Other bugs
- [ ] https://github.com/centerofci/mathesar/issues/3067
- [ ] https://github.com/centerofci/mathesar/issues/2724
- [ ] https://github.com/centerofci/mathesar/issues/3066
```

```[tasklist]
# User-requested improvements
- [ ] #3111
- [ ] #3069
- [ ] https://github.com/centerofci/mathesar/issues/3148
```

```[tasklist]
# Other improvements
- [ ] #3095
- [ ] #3143
- [ ] #3135
- [ ] #3128
- [ ] #2843
- [ ] #2304
- [ ] #1632
```

## Time estimate

I expect to get to **Other bugs** category, but not get through it during this cycle. The queue is significantly longer, because that will be useful when backend fixes will be picked up next cycle.

**Comment by seancolsen** [comment]
I'm closing this because I don't think we're planning to do any more of this work for v0.1.4 and the remaining work is still tracked in other tickets.
