### ISSUE TITLE
Release 0.1.3

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#3149]
## 2023-08-16
```[tasklist]
### Tasks
- [x] Cut 0.1.3 release branch, freeze code
- [x] Update version number in all places in the new branch
- [x] Make an image from the branch with tag `0.1.3`, push to Dockerhub
- [x] Test installation with the new image
- [x] Test upgrade
- [x] Smoke testing application
- [ ] Stability of the newly released items
```

**Comment by mathemancer** [comment]
While testing, I discovered a critical regression: #3160 .

I'm going to switch context to sort that out now.
