### ISSUE TITLE
2023-08 Front end work

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#3150]
```[tasklist]
# Issues
- [ ] https://github.com/centerofci/mathesar/pull/3037
- [ ] https://github.com/centerofci/mathesar/issues/1771
- [ ] https://github.com/centerofci/mathesar/issues/2342
- [ ] https://github.com/centerofci/mathesar/issues/2984
```

## See also

- #3144
- #3151
