### ISSUE TITLE
2023-08 Fullstack fixes

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#3151]
This is the issue queue for fullstack fixes for cycle 2 that's starting in 2023-08.

Compliments frontend and backend miscellaneous tasks:
- #3144
- #3150 

```[tasklist]
# Priority
- [ ] https://github.com/centerofci/mathesar/issues/3069
- [ ] https://github.com/centerofci/mathesar/issues/3143
```

```[tasklist]
# Maybe
- [ ] https://github.com/centerofci/mathesar/issues/1421
- [ ] https://github.com/centerofci/mathesar/issues/2202
- [ ] https://github.com/centerofci/mathesar/issues/3066
```

**Comment by seancolsen** [comment]
I'm closing this because I don't think we're planning to do any more of this work for v0.1.4 and the remaining work is still tracked in other tickets.
