### ISSUE TITLE
Column Moving Improvements

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#3152]
This issue will track work connected to the [Column Moving Improvements](https://wiki.mathesar.org/en/projects/column-moving) project.

## Problem
It came to my attention during RSQLA1 that our column extraction and moving feature isn't complete, and the current state is sort of dangerous. In fact, I'm concerned the current state is so bad that attempts to use this feature could well lead to justified ragequits from Mathesar entirely. I've written some problems up in roughly descending order of priority (IMO).

The column moving operation has the potential for data loss, or at least for jumbling up the link in certain edge cases, e.g., if the foreign key was created outside of Mathesar and is on a text column rather than integer.

The column moving operation is one-way only. Currently, you can only move columns along a foreign key link from the referrer table to the referenced table. E.g., from a remainder table to an extracted table. This asymmetry is not portrayed to the user, and they could easily tinker themselves into an irreversible situation. 

Merging tables is not available from the UI. This means you can't un-extract your columns.

If you extract a foreign key column, you'll lose the foreign key link. Start with:

**Roster**

| id | Student Name | Student Email   | Subject | Grade | Teacher |
|---:|--------------|-----------------|---------|------:|--------:|
|  1 | Alice        | alice@yahoo.com | Math    |    73 |       2 |
|  2 | Alice        | alice@yahoo.com | Music   |    87 |       1 |
|  3 | Alice        | alice@yahoo.com | Reading |    93 |       1 |
|  4 | Bob          | bob@lycos.com   | Math    |    58 |       2 |
|  5 | Bob          | bob@lycos.com   | Music   |    94 |       3 |
|  6 | Bob          | bob@lycos.com   | History |    83 |       1 |

**Teachers**
| id | Name      | Email          |
|---:|-----------|----------------|
|  1 | Ms. Smith | asmith@abc.edu |
|  2 | Mr. Jones | bjones@abc.edu |
|  3 | Mrs. Li   | eli@abc.edu    |

Suppose The **Teacher** column references the **Teachers** table ID, and I want to extract the **Subject** and **Teacher** columns from the **Roster** table to create a new table. Currently, this breaks the foreign key link between the **Teacher** column and the **Teachers** table.

## Proposed solution

We need to start by determining what we want from the 'split table', 'move columns', and 'merge tables' features at a product level.

```[tasklist]
### Tasks
- [ ] Refuse to move columns when data loss may occur
- [ ] Make column moving work in both directions safely
- [ ] Enable merging linked tables from the UI
- [ ] Improve handling of foreign key columns when extracting
- [ ] #1437 
- [ ] #1490 
- [ ] #1433 
- [ ] #1681 
```

**Comment by kgodey** [comment]
Closing this, we will track column moving improvements and fixes in our roadmap (to be published soon).
