### ISSUE TITLE
Deployment tooling Checklist 2022-12

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#41]
In preparation for the first release, we need tooling and documentation to help users and admins deploy and manage Mathesar in different contexts.

## Tasks

- [ ] Set up separate `docs.mathesar.org` site for documentation.

The deployment-specific tasks are organized by different deployment types, and
the intent is to do lower-numbered deployment types before higher-numbered ones.

### Deployment Type 1

This deployment has the service and all DBs running in Docker containers managed by `docker-compose` as in our current dev setup. We would want to help the user configure things for a production environment.

- [ ] Tidy up installation script.
- [ ] Smooth configuration in this context.
  - [ ] Superuser
  - [ ] Django secret key
  - [ ] DB credentials and details (user DB, Django DB)
- [ ] Make production docker image build.
  - [ ] Tidy up build.
  - [ ] turn off `dev` flags.
  - [ ] avoid hot-loading files
  - [ ] `COPY` rather than mounting code
- [ ] Set up CI to publish image to dockerhub
- [ ] Write production `docker-compose.yml` to use that image rather than building.
- [ ] Document use of this setup on `docs.mathesar.org`.

### Deployment Type 2

This deployment has the web service and its Django model tables DB running in Docker containers managed by `docker-compose`, but the user DB is assumed to be running separately either on the same underlying machine, or a different server altogether. Example: running the `mathesar_service` and a DB container for Django model tables on a minimal EC2 instance, and having user tables on an RDS PostgreSQL instance. In addition to the pieces of type 1 above, we should need:

- [ ] Ensure installation script works in this context, modify if needed.
- [ ] Smooth configuration in this context. In addition to the config for type 1,
  - [ ] Ports (help avoid conflicts)
  - [ ] privileged `mathesar` user
  - [ ] privileged already-extant user for use in creating above `mathesar` user.
- [ ] Provide a method for creating and using a separate privileged `mathesar` user on the User DB, starting from given privileged already-extant user on the target user DB.
- [ ] Create separate `docker-compose` service (maybe separate file?) to launch this setup.
- [ ] Document use of this setup on `docs.mathesar.org`

### Deployment Type 3

This is the same as Type 2, except the Django tables are stored on a database not managed by Docker. This is not recommended for performance reasons (i.e., if the database is running on a different server from the web service container).

- [ ] Document this setup, and pros-cons on `docs.mathesar.org`

### Deployment Type 4

This is a 'bare-metal' (more likely, VPS) installation with the database and Django web service installed on the same machine.

- [ ] Determine suitability of our ansible playbooks for this (it necessary? Could it be replaced for most users by a set of instructions?)

Further steps are dependent on outcome of above.

### Deployment Type 5

This is a 'bare-metal' installation (as above), but with a DB in some remote location. Very little should change from Type 4.

### Other deployment targets

- [ ] Investigate one-click deployment solutions from PAASes
  - [ ] Choose one that seems appropriate.
  - [ ] Implement it.
- [ ] Provide targeted instructions for setting up reasonable architectures on AWS, GCP, and Azure.

**Comment by kgodey** [comment]
I would not recommend Heroku as the primary PaaS target since they just phased out their free plan a couple of weeks ago. Instead, I'd add a short task to review PaaS options and determine the first PaaS target.

**Comment by dmos62** [comment]
> turn off dev flags

Maybe we should keep dev flags on, to improve bug reports?

**Comment by mathemancer** [comment]
> I would not recommend Heroku as the primary PaaS target since they just phased out their free plan a couple of weeks ago. Instead, I'd add a short task to review PaaS options and determine the first PaaS target.

I didn't know that. Thanks for the heads up.

**Comment by mathemancer** [comment]
This work is now being tracked in #2034
