### ISSUE TITLE
Write integration tests for some important user scenarios

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#640]
## Problem

We need integration tests written for each user scenario so far so that we don't break things as we develop new features.

## Tests to add

- [ ] Add new empty table
- [ ] Import via clipboard
- [ ] Import via file
- [ ] Add schema
- [ ] Add column
- [ ] Add row
- [ ] Sort table by column
- [ ] Edit existing record
- [ ] Open tab
- [ ] Close tab
- [ ] Delete two records
- [ ] Increment table pagination
- [ ] Remove multi-column unique constraint
- [ ] Try to disallow NULL on a column with NULL values
- [ ] Add multi-column unique constraint

[discussion](https://matrix.to/#/!UnujZDUxGuMrYdvgTU:matrix.mathesar.org/$d_enIAaHE1sIa-N6czmXs3QBX8KsOrU89D_E4imjbBw?via=matrix.mathesar.org&via=matrix.org)

## Additional context

- Work on this is blocked by #639 
- #89

**Comment by silentninja** [comment]
@seancolsen Can this issue be marked as started?

**Comment by seancolsen** [comment]
@silentninja sure, I just marked it as started.
