### ISSUE TITLE
Design specifications for adding records

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#722]
When user adds a new record, the following scenarios need to be detailed out, along with user interactions, response and success/error/loading states.
  - [ ] Behaviour when records are grouped.
  - [ ] Clear/Revert action, to revert a erroneous cell value.
  - [ ] Behaviour w.r.t. pagination.
  - [ ] Content and count shown in pagination bar.
  - [ ] Behaviour w.r.t. sorting and filtering.
  - [ ] Do we persist records that are added but not saved due to an error, when user moves across pages/sorts/filters/groups?
   - [ ] Alerts when user moves pages, regarding clearing of unsaved records.
   - [ ] Displaying errors when multiple cells are erroneous in a single row.
   - [ ] Tab movement across rows?
   - [ ] Behaviour for creating new row when user tries to edit non-editable column/when only non-editable column is present.
  - [ ] Behaviour for in-place refresh during delete.
  - [ ] Auto scrolling when new record is added.

@ghislaineguerin This is a placeholder meta issue. Please feel free to split them up into smaller issues.

**Comment by kgodey** [comment]
This issue is no longer relevant.
