### ISSUE TITLE
Design for Table Relationship

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#754]
Placeholder design issues for setting up Table Relationships

- [ ] Design for record lookup dropdown
- [ ] Design for deleting a linked record
- [ ] Design for record edit dropdown
- [ ] Design for adding a record from a view
- [ ] Design for setting up table relationship with a new table
- [ ] Design for setting up table constraints
- [ ] Design for linking a non-empty column

**Comment by kgodey** [comment]
@ghislaineguerin Is this issue still relevant given the new plan in #243?

**Comment by ghislaineguerin** [comment]
> @ghislaineguerin Is this issue still relevant given the new plan in #243?

@kgodey I think we can close it. It is no longer relevant.
